import {Platform,Dimensions} from 'react-native'
import {StyleSheet} from 'react-native'
const {height: SCREEN_HEIGHT, width: SCREEN_WIDTH} = Dimensions.get('window');
import mConst from '../../../common/constants'
import mUtils from '../../../common/utils'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: mConst.white,
  },
  mainTitle: {
    fontFamily: 'Roboto-Light',
    fontSize: 22,
    textAlign: 'left',
    color: mConst.black,
  },
  magazinetitle: {
    fontSize: 16,
    fontFamily: 'Roboto-Medium',
    textAlign: 'left',
    color: '#000000',
  },
  mainTitle1: {
    fontFamily: 'Roboto-Bold',
    fontSize: 22,
    textAlign: 'left',
    color: mConst.black,
  },
  brandImg: {
    width: mUtils.wScale(52.5),
    height: mUtils.wScale(20),
  },
  subTitle: {
    fontFamily: 'Roboto-Bold',
    fontSize: 18,
    textAlign: 'left',
    color: mConst.black,
  },
  subTitle2: {
    fontFamily: 'Roboto-Light',
    fontSize: 13,
    textAlign: 'left',
    color: mConst.red,
  },
  modelTitle: {
    fontFamily: 'Roboto-Medium',
    fontSize: 15,
    textAlign: 'center',
    color: '#070708',
  },
  redTitle: {    
    fontSize: 11,
    lineHeight :15,
    textAlign: 'center',
    color: '#555',
    marginTop: mUtils.wScale(1),
  },
  modelTitle2: {    
    fontSize: 12,
    textAlign: 'center',
    color: '#ff0000',
  },
  buttonText: {
    fontFamily: 'Roboto-Bold',
    fontSize: 16,
    textAlign: 'center',
  },
  smallTitle: {
    fontFamily: 'Roboto-Bold',
    fontSize: 14,
    textAlign: 'left',
    color: mConst.black,
    marginBottom: mUtils.wScale(8),
  },
  smallTitle2: {
    fontSize: 14,
    textAlign: 'left',
    color: mConst.black,
  },
  smallTitle3: {
    fontSize: 14,
    textAlign: 'left',
    color: '#7ea1b2',
  },
  buttonOuterWrap : {
    flex:1,paddingHorizontal:mUtils.wScale(10),flexDirection:'row',
    marginBottom:mUtils.wScale(20),flexWrap:'wrap'
  },
  nullButtonWrap : {
    paddingVertical: mUtils.wScale(5),
    alignItems: 'center',
    justifyContent:'center',
    paddingHorizontal: mUtils.wScale(10),
  },
  selectButtonWrap : {
    display:'flex',
    paddingVertical: mUtils.wScale(5),
    borderRadius: mUtils.wScale(10),
    borderStyle: 'solid',
    borderColor : '#7ea1b2',
    backgroundColor : '#7ea1b2',
    borderWidth: 0.5,
    alignItems: 'center',
    justifyContent:'center',
    paddingHorizontal: mUtils.wScale(10),
    marginRight:mUtils.wScale(5),
    marginBottom:mUtils.wScale(5),
  },
  defaultButtonWrap : {
    display:'flex',
    borderRadius: mUtils.wScale(10),
    paddingVertical: mUtils.wScale(5),
    borderStyle: 'solid',
    borderColor : '#ccc',
    borderWidth: 0.5,
    alignItems: 'center',
    justifyContent:'center',
    paddingHorizontal: mUtils.wScale(10),
    marginRight:mUtils.wScale(5),
    marginBottom:mUtils.wScale(5),
    maxWidth:SCREEN_WIDTH*0.9
  },
  boxText: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    textAlign: 'left',
    color: '#555555',
  },
  boxText1: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    textAlign: 'left',
    color: '#999999',
  },
  postCode: {
    fontFamily: 'NotoSansKR-Medium',
    fontSize: 12,
    textAlign: 'center',
    color: mConst.white,
  },
  yesNo: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    textAlign: 'left',
  },
  yesNoBox: {
    width: '49%',
    paddingVertical: mUtils.wScale(10),
    borderStyle: 'solid',
    borderWidth: 0.5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: mUtils.wScale(10),
  },
  twiceButtonWrap : {
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center'
  },
  postBox: {
    backgroundColor: mConst.black,
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: mConst.borderGray,
    paddingHorizontal: mUtils.wScale(8),
    paddingVertical: mUtils.wScale(8),
  },
  emptyBar: {
    width: '100%',
    height: mUtils.wScale(6),
    backgroundColor: '#f6f6f6',
    marginVertical: mUtils.wScale(30),
  },
  emptyBar2: {
    width: '100%',
    height: mUtils.wScale(6),
    backgroundColor: '#f6f6f6',
    marginVertical: mUtils.wScale(5),
  },
  bottomButton: {
    width: '100%',
    paddingVertical: mUtils.wScale(18),
  },
  bottomButton2: {
    width: '100%',
    justifyContent:'center',
    alignItems:'center',
    height: mUtils.wScale(60)
  },
  layout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  layout1: {
    flexDirection: 'row',
    alignItems: 'center',
    height: mUtils.wScale(35),
  },
  layout2: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  box1: {
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: mConst.borderGray,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: mUtils.wScale(8),
    paddingVertical: mUtils.wScale(8),
  },
  box2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: mConst.borderGray,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: mUtils.wScale(8),
  },
  inputBox: {
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: mConst.borderGray,
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
    textAlign: 'left',
    color: '#555555',
    paddingHorizontal: mUtils.wScale(8),
    paddingVertical: Platform.OS === 'ios' ? mUtils.wScale(7) : mUtils.wScale(1.2),
  },
  replaceWrap : {
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectBox: {
    borderRadius: mUtils.wScale(1),
    paddingHorizontal: mUtils.wScale(5),
    paddingVertical: mUtils.wScale(5),
    borderWidth: 0.7,
    borderColor: mConst.borderGray,
  },
  selectText: {
    fontFamily: 'Roboto-Medium',
    fontSize: 12,
    textAlign: 'center',
  },
  inputBox1: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    textAlign: 'left',
    color: '#555555',
    paddingHorizontal: mUtils.wScale(8),
    paddingVertical: Platform.OS === 'ios' ? mUtils.wScale(7) : mUtils.wScale(1.2),
  },
  modelImg: {
    width: mUtils.wScale(157.5),
    height: mUtils.wScale(236.5),
  },
  moreImg: {
    width: mUtils.wScale(13),
    height: mUtils.wScale(13),
  },
  starImg: {
    width: mUtils.wScale(12),
    height: mUtils.wScale(12),
    marginTop: mUtils.wScale(1),
  },
  checkImg: {
    width: mUtils.wScale(12),
    height: mUtils.wScale(12),
    marginRight: mUtils.wScale(5),
  },
  plusImg: {
    width: mUtils.wScale(35),
    height: mUtils.wScale(35),
  },
  checkImg2: {
    width: mUtils.wScale(12),
    height: mUtils.wScale(12),
  },
  select: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  select2: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: 1,
    alignItems: 'flex-end'
  },
  selectImg: {
    width: mUtils.wScale(45),
    height: mUtils.wScale(45),
    marginBottom: mUtils.wScale(10),
  },
  selectImg2: {
    width: mUtils.wScale(220),
    height: mUtils.wScale(245),
    marginBottom: mUtils.wScale(10),
  },
  delImg: {
    width: mUtils.wScale(20),
    height: mUtils.wScale(20),
  },
  del: {
    position: 'absolute',
    zIndex: 1,
    right: 5,
    top: 5,
  },
  contactText: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    textAlign: 'left',
    color: '#555555',
  },
  contactList: {
    padding: mUtils.wScale(10),
  },
  calendar: {
    alignSelf: 'center',
    position: 'absolute',
    zIndex: 1,
    top: mUtils.wScale(247),
    width: '100%',
  },
  text1: {
    fontFamily: 'NotoSansKR-Medium',
    fontSize: 14,
    textAlign: 'left',
    color: '#000000',
  },
  bottom: {
    width: '100%',
    height: mUtils.hScale(50),
    backgroundColor: mConst.getBaseColor(),
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottom2: {
    width: '100%',
    height: mUtils.hScale(50),
    backgroundColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  twiceBottom: {
    width: '50%',
    height: mUtils.hScale(50),
    backgroundColor: mConst.getBaseColor(),
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomText: {
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
    color: mConst.white,
  },  
})
