require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'prMagnet' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  ##pod 'Firebase/Core', '< 7.0.0' 
  ##pod 'Firebase/Messaging', '< 7.0.0' 

    target 'prMagnetTests' do
        inherit! :complete
        # Pods for testing
    end

  # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
    post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
      end
    end
end