// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore
const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:253551c6-7097-4fdc-a823-06576ba56150",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_oOqP24bWn",
    "aws_user_pools_web_client_id": "7trpatgla90rt5i7ai7hmrk8u8",
    "oauth": {
        "domain": "fpr-prod-auth.auth.ap-northeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost/",
        "redirectSignOut": "http://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "fpr-prod-api-v1",
            "endpoint": "https://mrrwobfo8j.execute-api.ap-northeast-2.amazonaws.com/prod/v1",
            "region": "ap-northeast-2"
        },
        {
            "name": "fpr-prod-cdn-v1",
            "endpoint": "https://mrrwobfo8j.execute-api.ap-northeast-2.amazonaws.com/prod/cdn/v1",
            "region": "ap-northeast-2"
        },
        {
            "name": "fpr-prod-noneauth-v1",
            "endpoint": "https://mrrwobfo8j.execute-api.ap-northeast-2.amazonaws.com/prod/noneauth/v1",
            "region": "ap-northeast-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://67kzvn5ktzfshnspqbanzttejm.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "fpr-prod-file",
    "aws_user_files_s3_bucket_region": "ap-northeast-2",
    "aws_content_delivery_bucket": "fpr-prod-cms",
    "aws_content_delivery_bucket_region": "ap-northeast-2",
    "aws_content_delivery_url": "fpr-prod-src"
};
export default awsmobile;
